import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CiemneNuty(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 20))
        self.menubar.setObjectName("menubar")
        self.File = QtWidgets.QMenu(self.menubar)
        self.File.setObjectName("File")
        self.Edit = QtWidgets.QMenu(self.menubar)
        self.Edit.setObjectName("Edit")
        self.Format = QtWidgets.QMenu(self.menubar)
        self.Format.setObjectName("Format")
        self.Style = QtWidgets.QMenu(self.menubar)
        self.Style.setObjectName("Style")
        self.Help = QtWidgets.QMenu(self.menubar)
        self.Help.setObjectName("Help")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/новый-файл.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("Open")
        self.Save = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/сохранить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save.setIcon(icon1)
        self.Save.setObjectName("Save")
        self.Save_As = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/сохранить-все.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Save_As.setIcon(icon2)
        self.Save_As.setObjectName("Save_As")
        self.Undo = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/отменить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Undo.setIcon(icon3)
        self.Undo.setObjectName("Undo")
        self.Redo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/повторить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Redo.setIcon(icon4)
        self.Redo.setObjectName("Redo")
        self.Cut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/вырезать.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cut.setIcon(icon5)
        self.Cut.setObjectName("Cut")
        self.Copy = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/скопировать.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Copy.setIcon(icon6)
        self.Copy.setObjectName("Copy")
        self.Paste = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/вставить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Paste.setIcon(icon7)
        self.Paste.setObjectName("Paste")
        self.Select_All = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Images/отметить-все.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Select_All.setIcon(icon8)
        self.Select_All.setObjectName("Select_All")
        self.Print = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Images/печать.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Print.setIcon(icon9)
        self.Print.setObjectName("Print")
        self.Export_PDF = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/pdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export_PDF.setIcon(icon10)
        self.Export_PDF.setObjectName("Export_PDF")
        self.Exit = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Images/удалить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon11)
        self.Exit.setObjectName("Exit")
        self.Font = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Images/хирагана-ма.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Font.setIcon(icon12)
        self.Font.setObjectName("Font")
        self.Color = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Images/цвет.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Color.setIcon(icon13)
        self.Color.setObjectName("Color")
        self.Bold = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Images/жирный.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bold.setIcon(icon14)
        self.Bold.setObjectName("Bold")
        self.Italics = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Images/курсив.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Italics.setIcon(icon15)
        self.Italics.setObjectName("Italics")
        self.Underline = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Images/подчеркивание.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Underline.setIcon(icon16)
        self.Underline.setObjectName("Underline")
        self.Left = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Images/выровнять-по-левому-краю.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Left.setIcon(icon17)
        self.Left.setObjectName("Left")
        self.Centre = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Images/выровнять-по-центру.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Centre.setIcon(icon18)
        self.Centre.setObjectName("Centre")
        self.Right = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Images/выровнять-по-правому-краю.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Right.setIcon(icon19)
        self.Right.setObjectName("Right")
        self.Justify = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Images/выровнять-по-обоим-краям.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Justify.setIcon(icon20)
        self.Justify.setObjectName("Justify")
        self.About = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Images/информация.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.About.setIcon(icon21)
        self.About.setObjectName("About")
        self.AboutProgram = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Images/помощь.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AboutProgram.setIcon(icon22)
        self.AboutProgram.setObjectName("AboutProgram")
        self.New = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Images/создать.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.New.setIcon(icon23)
        self.New.setObjectName("New")
        self.File.addAction(self.New)
        self.File.addAction(self.actionOpen)
        self.File.addAction(self.Save)
        self.File.addAction(self.Save_As)
        self.File.addSeparator()
        self.File.addAction(self.Print)
        self.File.addAction(self.Export_PDF)
        self.File.addSeparator()
        self.File.addAction(self.Exit)
        self.Edit.addAction(self.Undo)
        self.Edit.addAction(self.Redo)
        self.Edit.addSeparator()
        self.Edit.addAction(self.Cut)
        self.Edit.addAction(self.Copy)
        self.Edit.addAction(self.Paste)
        self.Edit.addSeparator()
        self.Edit.addAction(self.Select_All)
        self.Format.addAction(self.Font)
        self.Format.addAction(self.Color)
        self.Style.addAction(self.Bold)
        self.Style.addAction(self.Italics)
        self.Style.addAction(self.Underline)
        self.Style.addSeparator()
        self.Style.addAction(self.Left)
        self.Style.addAction(self.Centre)
        self.Style.addAction(self.Right)
        self.Style.addAction(self.Justify)
        self.Help.addAction(self.About)
        self.Help.addAction(self.AboutProgram)
        self.menubar.addAction(self.File.menuAction())
        self.menubar.addAction(self.Edit.menuAction())
        self.menubar.addAction(self.Format.menuAction())
        self.menubar.addAction(self.Style.menuAction())
        self.menubar.addAction(self.Help.menuAction())
        self.toolBar.addAction(self.New)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.Save)
        self.toolBar.addAction(self.Save_As)
        self.toolBar.addAction(self.Print)
        self.toolBar.addAction(self.Export_PDF)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.Copy)
        self.toolBar.addAction(self.Cut)
        self.toolBar.addAction(self.Paste)
        self.toolBar.addAction(self.Undo)
        self.toolBar.addAction(self.Redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.Font)
        self.toolBar.addAction(self.Color)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.Bold)
        self.toolBar.addAction(self.Italics)
        self.toolBar.addAction(self.Underline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.Left)
        self.toolBar.addAction(self.Right)
        self.toolBar.addAction(self.Centre)
        self.toolBar.addAction(self.Justify)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CiemneNuty"))
        self.File.setTitle(_translate("MainWindow", "Файл"))
        self.Edit.setTitle(_translate("MainWindow", "Редактирование"))
        self.Format.setTitle(_translate("MainWindow", "Формат"))
        self.Style.setTitle(_translate("MainWindow", "Стиль"))
        self.Help.setTitle(_translate("MainWindow", "Помощь"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Открыть"))
        self.Save.setText(_translate("MainWindow", "Сохранить"))
        self.Save_As.setText(_translate("MainWindow", "Сохранить как"))
        self.Undo.setText(_translate("MainWindow", "Отменить"))
        self.Redo.setText(_translate("MainWindow", "Повторить"))
        self.Cut.setText(_translate("MainWindow", "Вырезать"))
        self.Copy.setText(_translate("MainWindow", "Копировать"))
        self.Paste.setText(_translate("MainWindow", "Вставить"))
        self.Select_All.setText(_translate("MainWindow", "Выбрать всё"))
        self.Print.setText(_translate("MainWindow", "Печать"))
        self.Export_PDF.setText(_translate("MainWindow", "Экспортировать в PDF "))
        self.Exit.setText(_translate("MainWindow", "Выход"))
        self.Font.setText(_translate("MainWindow", "Шрифт"))
        self.Color.setText(_translate("MainWindow", "Цвет"))
        self.Bold.setText(_translate("MainWindow", "Жирный"))
        self.Italics.setText(_translate("MainWindow", "Курсив"))
        self.Underline.setText(_translate("MainWindow", "Подчеркнутый"))
        self.Left.setText(_translate("MainWindow", "Выровнить по левому краю"))
        self.Centre.setText(_translate("MainWindow", "По центру"))
        self.Right.setText(_translate("MainWindow", "Выровнять по правому краю"))
        self.Justify.setText(_translate("MainWindow", "Выровнять по ширине"))
        self.About.setText(_translate("MainWindow", "Сведения"))
        self.AboutProgram.setText(_translate("MainWindow", "Сведения об программе"))
        self.New.setText(_translate("MainWindow", "Новый файл"))

# класс в котором открывается все это дело
class mywindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(mywindow, self).__init__()
        self.ui = Ui_CiemneNuty()
        self.ui.setupUi(self)


app = QtWidgets.QApplication([])
application = mywindow()
application.show()

sys.exit(app.exec())

